[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "sh -c \"npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && node dist/main\""
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
